[client]
host=127.0.0.1
port=3307

[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.0
datadir=C:/Users/rstra/Desktop/Rajat Application/SFA/mysql-local/data
port=3307
bind-address=127.0.0.1
tmpdir=C:/Users/rstra/Desktop/Rajat Application/SFA/mysql-local/tmp
log-error=C:/Users/rstra/Desktop/Rajat Application/SFA/mysql-local/mysql-error.log
